### ISSUE TITLE
Old Hungarian font have spelling problems with dlig ligatures

### ISSUE THREAD

**Issue by Kixidevel** [googlefonts/noto-source#215] opened 2020-07-04 10:09 UTC
Old Hungarian font can maka spelling problems "dlig" ligature automation, with cases "x" vs "ksz", "qu" vs "kv", "w" vs vv.
"x","qu","w" isn't part of Old Hungarian script, so those defined as ligatures. 
"x" generate "k"+"sz" letter combination,
"w" generate "v"+"v" letter combination,
"qu" generate "k"+"v" letter combination.
Problem is that, there are words, which have correct spelling forms with "k+sz", "v+v", "k+v" combination isn't  correct generated ligatures "x", "w","qu".
See the example cases:
![testcase_dlig](https://user-images.githubusercontent.com/32356899/86510340-1d063180-bdef-11ea-9986-9f586889fa1e.jpg)

**Comment by Kixidevel** [comment] 2020-07-06 08:04
@marekjez86 @google-admin 
That is final dlig remove pull request.
Please merge it.

**Comment by Kixidevel** [comment] 2020-07-30 16:21
@marekjez86 
Cold you help me, how could I switch of dlig tag only? If I switch off dlig tag, liga tag switch off too.

**Comment by Kixidevel** [comment] 2020-09-25 10:04
@dscorbett @marekjez86 
I close it, this issue might be resolved by keyboard layout with ZWNJ key.

**Comment by Kixidevel** [comment] 2020-11-10 14:00
@dscorbett @marekjez86 @google-admin 
I reopen It. The spelling problems might be resolved with the 3 critical ligatures ('x', 'q' and 'w') removing from the discrete ligatures.

**Comment by marekjez86** [comment] 2020-11-11 17:24
@dscorbett : David, I was holding off on merge because I didn't feel qualified to evaluate it... Could you provide some fedback on this?

**Comment by Kixidevel** [comment] 2020-11-11 18:50
@dscorbett : David, If you ask Hungarian peoples, please write them that my colleague wrote : >>  A "hüje" ismérve nálunk az, aki a tyúkszart is x-el írja, ezt csinálja most a Noto! <<
I think, if you write it to them, they  will understand, what's the problem!
I imagined an another compromise: in dlig section: everithing will be unchanged, just the ligatures "x", "w", "q" will have a difference: require ZWJ for these "letters" or "ligatures" inside of dlig section, too!

**Comment by dscorbett** [comment] 2020-11-11 19:42
@marekjez86, the issue is that sometimes, in Old Hungarian, a sequence like “kv” may look like two separate letters, or may be ligated. By default, Noto Sans Old Hungarian does not ligate such sequences, but it does provide two methods to get ligatures: ZWJ and 'dlig'.

The complication is that there are some ligatures which are now considered equivalent to specific Latin letters. For example, in original Old Hungarian, “ksz” could written as two glyphs or as a ligature: it was up to the writer’s discretion. However, modern users of Hungarian are used to distinguishing “ksz” from “x” when writing in Latin script, and they want to maintain that distinction when writing in Old Hungarian. The way to distinguish is that “ksz” never gets a ligature and “x” always gets a ligature. It is therefore no longer merely discretionary.

This PR removes the ligatures for the three sequences that correspond to the Latin-script “x”, “qu”, and “w”. (They are still available with ZWJ.) There is only one reason I can think of to do this. If a user generally wants discretionary ligatures but does not want these three specific ligatures, this PR lets them enable 'dlig' over the entire text. @Kixidevel, is this the use case you had in mind? (The currently necessary alternative is to enable 'dlig' only for the specific spans that should be ligated.)

If so, and if Google Fonts thinks that enabling 'dlig' over an entire buffer is sensible behavior, then I think this PR can be merged.

**Comment by Kixidevel** [comment] 2020-11-12 06:40
> @marekjez86, the issue is that sometimes, in Old Hungarian, a sequence like “kv” may look like two separate letters, or may be ligated. By default, Noto Sans Old Hungarian does not ligate such sequences, but it does provide two methods to get ligatures: ZWJ and 'dlig'.
> 
> The complication is that there are some ligatures which are now considered equivalent to specific Latin letters. For example, in original Old Hungarian, “ksz” could written as two glyphs or as a ligature: it was up to the writer’s discretion. However, modern users of Hungarian are used to distinguishing “ksz” from “x” when writing in Latin script, and they want to maintain that distinction when writing in Old Hungarian. The way to distinguish is that “ksz” never gets a ligature and “x” always gets a ligature. It is therefore no longer merely discretionary.
> 
> This PR removes the ligatures for the three sequences that correspond to the Latin-script “x”, “qu”, and “w”. (They are still available with ZWJ.) There is only one reason I can think of to do this. If a user generally wants discretionary ligatures but does not want these three specific ligatures, this PR lets them enable 'dlig' over the entire text. @Kixidevel, is this the use case you had in mind? (The currently necessary alternative is to enable 'dlig' only for the specific spans that should be ligated.)
@dscorbett : David, I didn't understand all words in your comment, but it seems, you understand the problem. So my answer is yes.
> 
> If so, and if Google Fonts thinks that enabling 'dlig' over an entire buffer is sensible behavior, then I think this PR can be merged.

**Closed** 2020-11-12 23:53 UTC
