### ISSUE TITLE
NotoSerifTibetan-VF.ttf produces different (incorrect) result than NotoSerifTibetan-Regular.ttf built from the same source

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-source#145] opened 2020-01-05 00:26 UTC
Source : https://github.com/googlefonts/noto-source/blob/master/src/NotoSerifTibetan-MM.glyphs

text: དཀྱོིར་ 
<img width="99" alt="Screen Shot 2020-01-04 at 16 21 53" src="https://user-images.githubusercontent.com/13322623/71773223-7360e900-2f0e-11ea-8d6d-56333fa61f92.png">

the result of rendering the text above on my Mac (using fontdiff -- NotoSerifTibetan-Regular.ttf is reddish on top, NotoSerifTibetan-VF.ttf is greenish on the bottom)

<img width="75" alt="Screen Shot 2020-01-04 at 16 23 53" src="https://user-images.githubusercontent.com/13322623/71773250-e9fde680-2f0e-11ea-861c-df72217db442.png">

there are more text samples that I will try to provide here

Note that NotoSerifTibetan is the only font out of 50+ Noto variable fonts that exhibits this behavior.

**Comment by marekjez86** [comment] 2020-01-05 00:52
the text:  ཥཾ་
<img width="101" alt="Screen Shot 2020-01-04 at 16 51 15" src="https://user-images.githubusercontent.com/13322623/71773474-73fb7e80-2f12-11ea-9fa1-45e17bca8e49.png">

the result of rendering the text above on my Mac (using fontdiff -- NotoSerifTibetan-Regular.ttf is reddish on top, NotoSerifTibetan-VF.ttf is greenish on the bottom)

<img width="107" alt="Screen Shot 2020-01-04 at 16 52 09" src="https://user-images.githubusercontent.com/13322623/71773484-955c6a80-2f12-11ea-8823-bb0084439383.png">

**Comment by marekjez86** [comment] 2020-01-05 01:09
I exported variable font using glyphs (see below)
[NotoSerifTibetanGX.ttf.zip](https://github.com/googlefonts/noto-source/files/4022786/NotoSerifTibetanGX.ttf.zip)


Then I compared the visible results using a new tool fontgoggles.

Our VF font using the last test string
<img width="794" alt="Screen Shot 2020-01-04 at 17 03 08" src="https://user-images.githubusercontent.com/13322623/71773617-b0c87500-2f14-11ea-8df7-aa340e30d753.png">

GX font
<img width="817" alt="Screen Shot 2020-01-04 at 17 04 07" src="https://user-images.githubusercontent.com/13322623/71773626-c9388f80-2f14-11ea-8360-494a9355a0d8.png">

The main difference GX has <delta>X equal to -179 for U+0F7E and we do not.

**Comment by marekjez86** [comment] 2020-01-05 01:25
I was curious about the first (initial test string) in gontgoggles

Out VF
<img width="799" alt="Screen Shot 2020-01-04 at 17 22 50" src="https://user-images.githubusercontent.com/13322623/71773720-fab25a80-2f16-11ea-862a-94fa398e0da1.png">
GX
<img width="817" alt="Screen Shot 2020-01-04 at 17 21 52" src="https://user-images.githubusercontent.com/13322623/71773723-0867e000-2f17-11ea-93f8-b82c1bdc6d06.png">

deltaY is virtually the same for both fonts but deltaX appears to be different

**Comment by punchcutter** [comment] 2020-01-05 07:09
In the GPOS lookup for this mark to base attachment the anchor for the mark (oMatra_tibet.2) exists, but the corresponding anchor for the base (ka_yaSub_tibet) is missing in the variable font. It's fine in the static instance.

**Comment by marekjez86** [comment] 2020-01-06 02:58
@punchcutter : thanks for the details and looking at the cause

**Comment by punchcutter** [comment] 2020-01-06 03:46
I looked into it more and it looks like the GPOS is all there, but it's split into an Extension Lookup and somehow that's not working properly. I'm not entirely sure why yet.

**Comment by punchcutter** [comment] 2020-01-06 07:25
I dumped the GX and VF GPOS tables with ttx and compared and the VF has all the info, but the way the VF is written has the classes written in a way that doesn't work. For the first example above for oMatra_tibet.2 the MarkRecord is written out like this
```
              <MarkRecord index="80">
                <Class value="4"/>
                <MarkAnchor Format="1">
                  <XCoordinate value="380"/>
                  <YCoordinate value="678"/>
                </MarkAnchor>

```

If I change Class value to "1" then it works correctly, but that's just luck. The BaseRecord for ka_yaSub_tibet isn't written correctly. From the GX font the record is complete like this

```
<BaseRecord index="171">
                <BaseAnchor index="0" Format="3">
                  <XCoordinate value="367"/>
                  <YCoordinate value="-217"/>
                  <XDeviceTable>
                    <StartSize value="0"/>
                    <EndSize value="158"/>
                    <DeltaFormat value="32768"/>
                  </XDeviceTable>
                  <YDeviceTable>
                    <StartSize value="0"/>
                    <EndSize value="676"/>
                    <DeltaFormat value="32768"/>
                  </YDeviceTable>
                </BaseAnchor>
                <BaseAnchor index="1" Format="3">
                  <XCoordinate value="633"/>
                  <YCoordinate value="-257"/>
                  <XDeviceTable>
                    <StartSize value="0"/>
                    <EndSize value="158"/>
                    <DeltaFormat value="32768"/>
                  </XDeviceTable>
                  <YDeviceTable>
                    <StartSize value="0"/>
                    <EndSize value="676"/>
                    <DeltaFormat value="32768"/>
                  </YDeviceTable>
                </BaseAnchor>
                <BaseAnchor index="2" Format="3">
                  <XCoordinate value="640"/>
                  <YCoordinate value="678"/>
                  <XDeviceTable>
                    <StartSize value="0"/>
                    <EndSize value="159"/>
                    <DeltaFormat value="32768"/>
                  </XDeviceTable>
                </BaseAnchor>
                <BaseAnchor index="3" Format="3">
                  <XCoordinate value="374"/>
                  <YCoordinate value="678"/>
                  <XDeviceTable>
                    <StartSize value="0"/>
                    <EndSize value="160"/>
                    <DeltaFormat value="32768"/>
                  </XDeviceTable>
                </BaseAnchor>
                <BaseAnchor index="4" Format="1">
                  <XCoordinate value="90"/>
                  <YCoordinate value="678"/>
                </BaseAnchor>
                <BaseAnchor index="5" Format="3">
                  <XCoordinate value="640"/>
                  <YCoordinate value="678"/>
                  <XDeviceTable>
                    <StartSize value="0"/>
                    <EndSize value="159"/>
                    <DeltaFormat value="32768"/>
                  </XDeviceTable>
                </BaseAnchor>
                <BaseAnchor index="6" empty="1"/>
              </BaseRecord>
```
There are anchors for all possible marks, in this case 0-5 which can be seen in the generated FDK source 

`pos base ka_yaSub_tibet <anchor 367 -217> mark @MC_bottom <anchor 633 -257> mark @MC_bottomright <anchor 640 678> mark @MC_flag <anchor 374 678> mark @MC_top <anchor 90 678> mark @MC_topleft <anchor 640 678> mark @MC_topright;`

The VF font doesn't seem to get the complete BaseRecord which is why this isn't working. Seems like something wrong in fonttools.

**Comment by anthrotype** [comment] 2020-01-07 12:32
Thanks Marek and Zachary for finding this bug!
I can confirm it's a bug in the fonttools code which splits a MarkBasePos subtable in two halves containing half of the mark classes when offsets overflow. The MarkRecord.Class values in the new split subtable were incorrectly kept as they were in the original merged subtable, whereas they should be updated to reflect the new ClassCount // 2.
The base records implicitly define one anchor per mark class starting at 0; since the class values were out of sync, no attachments were made.
I'll fix this in fonttools.

**Closed** 2020-01-07 15:02 UTC

**Comment by marekjez86** [comment] 2020-01-07 16:03
Thanks Cosimo and Zachary!
