### ISSUE TITLE
Fonts with incorrect "OS/2" tables

### ISSUE THREAD

**Issue by kkartaltepe** [googlefonts/noto-source#375] opened 2021-05-18 05:22 UTC
Verified with `ttfdump` utility output.

The PANOSE element of the OS/2 table for Noto Serif Khojki Regular font reports `Serif Style:    11      'Normal Sans'` 

The PANOSE element of the OS/2 table for Noto Sans Medefaidrin Regular font reports `Serif Style:    2   'Cove'`

**Comment by twardoch** [comment] 2021-05-18 06:23
It would make sense to sync all PANOSE data in Noto fonts. I believe that Windows uses PANOSE to pick closest matches for fallback.

**Comment by simoncozens** [comment] 2022-03-26 21:27
Closing as duplicate of #363.

**Closed by simoncozens** 2022-03-26 21:27 UTC
